databases:
  - name: project
    plan: free
    databaseName: project_db
    user: project_db_user

services:
  - type: web
    plan: free
    name: project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
